# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10)),
                ('course', models.CharField(blank=True, choices=[('BTECH', 'B. Tech.'), ('MTECH', 'M. Tech.'), ('MCA', 'MCA')], max_length=10)),
                ('year', models.CharField(blank=True, choices=[('YEAR1', '1st year'), ('YEAR2', '2nd year'), ('YEAR3', '3rd year'), ('YEAR4', '4th year')], max_length=10)),
                ('registered', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mem1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='team.Student')),
                ('mem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='team.Student')),
                ('mem3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='team.Student')),
                ('mem4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='team.Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
