# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170121_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
