# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_auto_20170121_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvedusers', to='contest.Question')),
                ('userteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvedteam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
